### ISSUE TITLE
Fix Library Search links issue (Google Analytics)

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/web-enhance#11]
Library Search links, when clicked, open up a Library Search page without the hero image, and additional info (likely Google Analytics info) in the URL:

Page example:

https://prod.libraries.emory.edu/materials/audiobooks

Library Search link example:

https://search.libraries.emory.edu/?_ga=2.173649699.1887250774.1646057739-275011687.1644445979

**Comment by eporter23** [comment]
@lovinscari I believe this was resolved a few months back. We did work on the Library Search side to accommodate those link parameters from Google Analytics.
