### ISSUE TITLE
default to phrase style searching on databases pages, similar to site search 

### ISSUE THREAD

**Issue by mjander2** [emory-libraries/web-enhance#17]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
The site search seems to search things as a phrase, e.g. business source complete returns the database as the top result.   The business database page search seems to default as a single word/any words, as a search for business source complete returns a whole long list of databases, with business source complete way down the list.  

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
Since site search appears to look for phrases, I would expect the same function could be used for the database search box? 

**Describe the solution you'd like**
I would like for folks to see the expected search result near the top of their list.  This could be by including more than just the title of the database, so searching the description too, or changing the search strategy. 
Other database examples that cause problems are atozdatabases, standard & poors net advantage.  I'm not sure if there is anything we can do about the & being a problem... in Cascade we have several meta data tags to help with searches and I'm not sure what the drupal version of that would be/ 

**Describe alternatives you've considered**
We encourage users to use quotes for database phrases, or to browse by alpha order. We've also added "hacks" to the titles, e.g. BSC, SnP, etc.  

**How will this impact users?**
Less experienced searchers get very confused searching for a phrase on the database page and getting results that are sometimes less accurate than when they use the site search box!  

**Additional context**

**Comment by CB987** [comment]
need to switch the databases search from content to search api in order to implement the change. Bryan started work on 2nd zoom from 1017.

**Comment by CB987** [comment]
https://stage.libraries.emory.edu/business/research-learning/databases?
I also realized that i have to fix the search term (not) being sticky. moving back to in progress for that.

**Comment by CB987** [comment]
PR #[862](https://github.com/emory-libraries/d9-emory-libraries/pull/862) has sticky search term and fixes a styling problem i also noted.
hopefully will be released to stage in 2.0.3

**Comment by cwbragg** [comment]
@CB987 Ready for Review/QA

**Comment by cwbragg** [comment]
@CB987 This ticket is from a while ago! Was this released to prod?

**Comment by CB987** [comment]
yes, confirmed that it is on prod.
