### ISSUE TITLE
Migrate the Records Management site to Drupal.

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-enhance#2]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
The [Records management site](https://records.emory.edu/) is difficult to maintain because it is in Drupal.

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
The Records Management site is currently in Cascade and we no longer want to support Cascade

**Describe the solution you'd like**
The website should be migrated to Drupal as a multisite. The domain name should be migrated Acquia's infrastructure. The content should be migrated wholesale unless the records management staff has a desire to overhaul the website content. The Cascade site needs to be decommissioned. End users that have links bookmarked should automatically redirect to the content's location on the new site.  

**Describe alternatives you've considered**
Leaving the site in Cascade and continuing to support it there.

**How will this impact users?**
The Records Management site had roughly 2,500 users in the Jan - Jun 2022 period. The Records Management Staff will have an easier time maintaining their website.  LTDS and CCR will no longer have to support Cascade.

**Additional context**

**Comment by cwbragg** [comment]
All related tickets are closed, and the project has been completed.
