### ISSUE TITLE
Oxford Library Component Box that displays new books

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/web-enhance#21]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
Submitted by Ben Brown - I would like to create a component box on our homepage that displays New Books we have recently added to our collection. Is there a way to automate this, to setup a component box in Drupal that will automatically display images of new books recently added to our collection, pulling a feed from Alma? If not, could we add something like this to an enhancement request list?

**Is your feature request related to a problem or a change to existing functionality? Please describe.**

**Describe the solution you'd like**
I would like to create a component box on our homepage that displays New Books we have recently added to our collection. Is there a way to automate this, to setup a component box in Drupal that will automatically display images of new books recently added to our collection, pulling a feed from Alma? If not, could we add something like this to an enhancement request list?

**Describe alternatives you've considered**
None

**How will this impact users?**
This will provide information for end uses wanting to know new books available in Oxford Library in a visual manner

**Additional context**

**Comment by CB987** [comment]
Maybe try using Feeds Extensible and Tamper API module to map/parse the data
https://www.drupal.org/project/feeds_ex
https://www.drupal.org/project/feeds_tamper
need to see what the data looks like

**Comment by maxdmayhew** [comment]
Rest or Feeds / Feeds TAMPER

**Comment by CB987** [comment]
something like this exists in search already based on a script that Alex Cooper in core systems developed... i'd say we see if we can piggyback off of that instead of recreating the wheel pulling from alma if we do this.

**Comment by rotated8** [comment]
Rather than implementing something in the website to accomplish this, please link to the catalog using the facets that already exist. For newly acquired items at Oxford, that would be https://search.libraries.emory.edu/?f%5Blibrary_ssim%5D%5B%5D=Oxford+College+Library&f%5Bmarc_resource_ssim%5D%5B%5D=Recently+Acquired

**Comment by lovinscari** [comment]
@cwbragg - Can you please coordinate with Ben to see if this satisfies the enhancement request? Thanks!

**Comment by cwbragg** [comment]
@lovinscari Will do. I've sent the comment and link Collin provided to Ben directly for feedback.

**Comment by cwbragg** [comment]
@lovinscari @rotated8 Collin's suggestion satisfies the request. We can close the ticket.
