### ISSUE TITLE
Hyperlink RSS Feed in a Drupal Black 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/web-enhance#22]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
Enhancement Request for Emory Libraries Drupal sites: could the title of an RSS feed in a Drupal Block be a hyperlink back to the homepage of the original site? For example, hyperlinking the Drupal block title "Oxford Library Blog" at the bottom of oxford.library.emory.edu homepage back to our blog's homepage.

Thanks,
Ben.

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
No

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
N/A

**How will this impact users?**
This will provide a way for users to return to the home page

**Additional context**

**Comment by CB987** [comment]
Have asked Ben: From what we’ve looked at, we don’t immediately see a path to adding a hyperlink to the title of the feed. However, it would be very straightforward to add a button to the bottom of the feed, with whatever wording seems appropriate to you, that would take users to the main blog page. This is how the news and event feeds work on the default home page, you can see it at the bottom of libraries.emory.edu, and it is also more accessibility-friendly. Would that solution work for you?

**Comment by maxdmayhew** [comment]
added the link to prod, but it currently does not open in a new tab. Currently reads as "View all blog post", going to make sure that's okay with Ben.

Need to add this to dev/main.

**Comment by lovinscari** [comment]
@lovinscari will follow up with Ben to see if the solution is satisfactory.

**Comment by cwbragg** [comment]
Prod has the "view all blog posts" button at the bottom of the block. We can close this and reopen if necessary.
