### ISSUE TITLE
Larger location field window in service hour exception node edit

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#26]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
No

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
Change, it's a tweak to an edit screen for easier selecting

**Describe the solution you'd like**
When creating a service hours exception, the location field window is very small. It takes time to scroll to find the desired locations to select, and once selected one cannot see all of the locations at once.

A larger window to aid seeing all selected choices would be a great benefit to czars in change of adding service hours exceptions to the site. 

**Describe alternatives you've considered**
Creating an exception for single locations, one at a time. This would increase the amount of time spent adding exceptions.

**How will this impact users?**
This will impact czars and the speed at which they can create hours and exception nodes. 

![small location window - service hours exception](https://user-images.githubusercontent.com/58950697/216669806-117fbe5b-46df-40f9-8c08-99b83c00f6ae.png)

**Comment by CB987** [comment]
@cwbragg  Would this work?
![Screenshot 2024-01-03 at 7 22 30 PM](https://github.com/emory-libraries/web-enhance/assets/43180845/0f9312d4-9667-48c4-85e2-8b09c374f4a6)
(In admin/structure/types/manage/service_hours_exception/form-display changed Location from SelectList to Checkboxes/Radio Buttons)

**Comment by CB987** [comment]
Or this option, Select2, is kind of a combo 
![Screenshot 2024-01-03 at 7 25 41 PM](https://github.com/emory-libraries/web-enhance/assets/43180845/76aca258-8aea-4d71-a287-c5fcf4186e2e)

**Comment by CB987** [comment]
per @cwbragg, we're going to go with the first option of checkboxes.

**Comment by CB987** [comment]
PR #[885](https://github.com/emory-libraries/d9-emory-libraries/pull/885)

**Comment by CB987** [comment]
merged to dev/main.

**Comment by cwbragg** [comment]
@CB987 Ready for deploy to stage.

**Comment by cwbragg** [comment]
Checkboxes have been implemented on prod. Closing the ticket.
