### ISSUE TITLE
Service hours exception dashboard: sort by affected dates

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#27]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
No

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
The moderation dashboard doesn’t allow one to sort the list by affected dates, locations, etc. 

**Describe the solution you'd like**
Sorting by columns in the dashboard, which will help users see their additions sorted by date. This will greatly help with proofreading their list for any missing exceptions.

**Describe alternatives you've considered**
Using the filters to thin out the list, but it still takes a lot of time to read through the dates, since they are out of order (listed by order of creation date/time)

**How will this impact users?**
It will make life much easier for czars to sort the multitude of exceptions by date. 

**Additional context**
Image of affected dates, currently displayed only by date created...
![service hour exception dashboard affected dates](https://user-images.githubusercontent.com/58950697/216670389-271f9dbc-56ea-43c0-9fe9-668da39c67e0.png)

**Comment by maxdmayhew** [comment]
this needs to be exported, in my current local site.

**Comment by lovinscari** [comment]
@cwbragg and @maxdmayhew - can the two of you please get together to coordinate the testing of this since I'm not sure if this is still on Max's local site? Please close the ticket once the functionality is confirmed.

**Comment by cwbragg** [comment]
@maxdmayhew @lovinscari This is now live on prod - Max set the affected dates to always start with the most distant date at the top. It can be closed.
