### ISSUE TITLE
Fix text box component element style “Paragraph listing” font formatting for hyperlinks 

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#29]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
no

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
The Paragraph Listing element style is not fully configured, in that hyperlinked text loses the font style.

**Describe the solution you'd like**
Hyperlinked text is formatted so it is the same font as unlinked text in Paragraph Listing

**Describe alternatives you've considered**
Not using this element style, or removing it

**How will this impact users?**
Accessibility: changing fonts within a block of text can be visually confusing.

**Additional context**
Example image
![paragraph listing](https://user-images.githubusercontent.com/58950697/216673437-7a68285e-4682-4e81-a4b7-9866f35e9576.png)

**Comment by cwbragg** [comment]
We tend to use "Paragraph Lead" styling at the top of pages.

**Comment by CB987** [comment]
link text in paragraph listing style:
<img width="395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzQ4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03a629b6cc35e69eea92b899f9ffd1301265b967/Screenshot%202023-12-06%20at%208.05.58%E2%80%AFPM.png" alt="Screenshot 2023-12-06 at 8.05.58 PM.png" />
on hover:
<img width="388" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEE4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6294d84013f9048100b659c651344fefeb5c69af/Screenshot%202023-12-06%20at%208.06.35%E2%80%AFPM.png" alt="Screenshot 2023-12-06 at 8.06.35 PM.png" />

**Comment by CB987** [comment]
@cwbragg let me know if that is what you are looking for or if not, what changes you'd like to see. 
branch is we29-listing-paragraph-link and draft PR #[879](https://github.com/emory-libraries/d9-emory-libraries/pull/879)

**Comment by CB987** [comment]
merged to main/ on dev

**Comment by cwbragg** [comment]
@CB987 @lovinscari This is looking good to me, and is now similar to the Paragraph Lead style. Let's go with it.

**Comment by cwbragg** [comment]
@CB987 Ready for deploy to stage

**Comment by cwbragg** [comment]
The work has been completed and is on prod.
