### ISSUE TITLE
Cannot Drag Hour Rows Up and Down 

### ISSUE THREAD

**Issue by bbrown8** [emory-libraries/web-enhance#32]
I am on the Service Hours Moderation Dashboard for the Oxford Library's Hours page. I would like to flip the order of our "Virtual Hours" and "Oxford Library Hours" rows, and I know some users have the ability to click and drag these rows to change the order they appear in. But on my end, I cannot see the "click and drag arrows" in any browser I try (Chrome, Firefox, Safari). Is this a bug?

![What Colin Sees](https://user-images.githubusercontent.com/114684814/222534770-9922a082-47f6-41b7-9f7b-ae2ee442a437.png)

<img width="172" alt="What Ben Sees" src="https://user-images.githubusercontent.com/114684814/222534790-14cba3c5-ecf5-46a8-8da1-9d4d2f1ece17.png">

**Comment by lovinscari** [comment]
@cwbragg to troubleshoot this
