### ISSUE TITLE
Drupal timeline module

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#34]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
A clear and concise description of what the new feature will provide. 

New functionality. The Health Sciences Library is hoping to reproduce a timeline featured on the SOM site:
https://med.emory.edu/about/history/timeline/index.html 

There is a module for that!  
https://www.drupal.org/node/561540

**Is your feature request related to a problem or a change to existing functionality? Please describe.**

Problem: recreating the sizing and spacing of the SOM timeline is difficult without an easy way to manipulate tables. 

**Describe the solution you'd like**
With the addition of a timeline module, the formatting would be simple and more accessible.

**Describe alternatives you've considered**

Using columns and containers to size images and date content, and possibly bullet points or periods to create the visual continuity of the SOM page. This may or may not be mobile-friendly.

**How will this impact users?**
The page would be more easily edited and a viewable across devices.

**Additional context**
Here is a first attempt at creating a timeline using our existing Drupal components:
https://stage.libraries.emory.edu/health/timeline-test

**Comment by cwbragg** [comment]
There is only one page across the sites that features a timeline: https://libraries.emory.edu/health/about/whsc-library-timeline

Since the page is live and they seem happy with it, I think this ticket could be closed or mothballed.

**Comment by rotated8** [comment]
Current page will work, so we don't need to implement this.
