### ISSUE TITLE
Install "publication date" module for new page reporting 

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#35]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
New feature: https://www.drupal.org/project/publication_date    

**Is your feature request related to a problem or a change to existing functionality? Please describe.**

The content overview page only shows latest Published date - there is seemingly no way to currently see the initial publication of content. CCR needs to report new content to SMT via content calendars. This module would assist in easily obtaining what has recently been created.

**Describe the solution you'd like**
Once the module is added, admin (and czars) can easily sort the overview list by publication date. 

**Describe alternatives you've considered**
Web content strategist asking czars for pages on a regular basis, or spending time opening individual content and searching for first date in revision tab. 

**How will this impact users?**
It will speed up the content reporting process exponentially! 

**Additional context**
Add any other context or screenshots about the feature request here. (image of the current content overview window table)
<img width="1326" alt="Screen Shot 2023-05-12 at 9 12 57 AM" src="https://github.com/emory-libraries/product-enhance/assets/58950697/2e5730c9-50a8-40ff-b514-c5423753b16d">

**Comment by maxdmayhew** [comment]
Lets discuss this. We may be able to do this without a module (ideal)

**Comment by rotated8** [comment]
Add Authored On as "Created" to the content admin dashboard, and make it sortable. Also make "Author" sortable too.

**Comment by lovinscari** [comment]
@cwbragg - I think you will need to test this one. Thanks!

**Comment by cwbragg** [comment]
@lovinscari @maxdmayhew This looks great. I can sort by author, status, created, and updated.

**Comment by cwbragg** [comment]
@lovinscari @maxdmayhew I will reach out to John Mills on this.
