### ISSUE TITLE
Embedding HTML game into Drupal page

### ISSUE THREAD

**Issue by bbrown8** [emory-libraries/web-enhance#38]
Oxford Library staff would like to embed an HTML-based [Twine game](https://twinery.org/) into a Drupal page. Twine games do not generate an iFrame or other embed code, only an HTML source code. I have tried to embed the game in a Drupal page using the native Drupal text editor by pasting the HTML source code into a Text component, but Drupal does not read it.  The staff have sent me an HTML file for this game which I can share, but it will not attach to this request. Is there another way in which I might display this HTML-based game in Drupal?

**Comment by maxdmayhew** [comment]
can you send us the html file? eand we'll see what we can do!

@cwbragg

**Comment by rotated8** [comment]
Another solution would be to create an itch.io account, upload the game there (they are popular for hosting Twine games), and use itch to produce the iframe to embed

**Comment by cwbragg** [comment]
I've informed Ben about itch.io, which he said he would try out. I'll follow up once he gets to it.

**Comment by cwbragg** [comment]
From Ben: Here is the embed code they sent me from the itch.io account:

<iframe frameborder="0" src="https://itch.io/embed-upload/9295303?color=333333" allowfullscreen="" width="640" height="380"><a href="https://oxlib.itch.io/oxford-college-library">Play Oxford College Library Tour on itch.io</a></iframe>

**Comment by cwbragg** [comment]
`<iframe frameborder="0" src="https://itch.io/embed-upload/9295303?color=333333" allowfullscreen="" width="640" height="380"><a href="https://oxlib.itch.io/oxford-college-library">Play Oxford College Library Tour on itch.io</a></iframe>`

**Comment by CB987** [comment]
the above code entered into the wysiwyg as source code and adding https://itch.io/ to the frame-src in the seckit settings works.<img width="675" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOStiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6817e2132fd2d66db8dcafe7f6e07171b246c2d1/Screenshot%202024-02-28%20at%207.53.53%E2%80%AFPM.png" alt="Screenshot 2024-02-28 at 7.53.53 PM.png" />
