### ISSUE TITLE
Spike: Determine work involved to create a department view for the staff directory. 

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-enhance#4]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
Make staff viewable based on departments or the larger organizational structure.

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
Currently, you can view the library staff directory by library location, but it does not allow us to view staff based on departments.

**Describe the solution you'd like**
Determine a way to make staff viewable based on the organization’s structure. This might include incorporating in a clickable org chart (see [Vanderbilt Library](https://www.library.vanderbilt.edu/staff/org-chart.html)) or so that users can filter by department or division (see [Penn State Libraries](https://libraries.psu.edu/directory)).

**Describe alternatives you've considered**
Staying with the status quo.

**How will this impact users?**
The contact section of the website received around 14,000 page views in Jan - Jun 2022. The vast majority are within the staff-directory.

**Additional context**

**Comment by maxdmayhew** [comment]
duplicate ticket, closing
