### ISSUE TITLE
Trumba feed block for SCO landing page

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#40]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
The functionality is there for the main site, a Drupal block for a Trumba feed. 

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
Related to the SCO migration.

**Describe the solution you'd like**
A Drupal block displaying the Trumba feed specific to SCO workshops. 
A whole[ calendar of events ](https://libraries.emory.edu/events-exhibits/event-list) view for SCO would likely be overkill - perhaps the event links would lead directly to https://www.trumba.com/calendars/woodruff-classes-scholarly-communication

**Describe alternatives you've considered**
A content card that doesn't display upcoming workshops with a link that goes to https://www.trumba.com/calendars/woodruff-classes-scholarly-communication

**How will this impact users?**
Users could see what SCO-specific workshops are available without navigating away from the site.

**Comment by CB987** [comment]
<img width="338" alt="Screenshot 2024-01-05 at 5 18 45 PM" src="https://github.com/emory-libraries/web-enhance/assets/43180845/7f13217d-a8aa-443f-b917-862c206ebf64">
sco events on the left

**Comment by CB987** [comment]
@cwbragg let me know if that looks good or if there are any changes . the part on the page is content, of course, and would be created directly on the page once the new events feed block gets released to prod.

**Comment by CB987** [comment]
<img width="1116" alt="Screenshot 2024-01-05 at 7 20 32 PM" src="https://github.com/emory-libraries/web-enhance/assets/43180845/6cef43b9-9659-4bc1-8b9b-914c22d1640b">
@cwbragg final product?

**Comment by CB987** [comment]
[PR#887](https://github.com/emory-libraries/d9-emory-libraries/pull/887)

**Comment by cwbragg** [comment]
@CB987 Ready for deploy

**Comment by cwbragg** [comment]
SCO Trumba feed block now on PROD. No current events, but can be added to the SCO landing page at any time. I'll close this ticket
