### ISSUE TITLE
Creation of staff directory views for departments

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#41]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
No, directory views are being utilized for all staff, subject librarians, Business Library librarians/staff, Health informationists/staff, etc.

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
Both SCO and Access Services have inquired about staff directories for their teams. Those views utilize taxonomy/location or subject area for filtering, so I am not certain what could be used for departments (maybe tags?)

**Describe the solution you'd like**
Staff directory views filtered by department name or similar. 

**Describe alternatives you've considered**
Creating staff pages "manually." Example:
https://libraries.emory.edu/services/scholarly-communications/staff

**How will this impact users?**
Multiple departments could benefit from this. Staff changes would be automatically reflected in these views, and content would not need be tracked and modified in multiple locations.

**Comment by lovinscari** [comment]
This ticket will be addressed as part of ticket #693.
