### ISSUE TITLE
Create new content card component with text editor (SCO project request)

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#42]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
Newish feature. Modify or create new content card component that includes text editor (and ability to add hyperlinks)

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
Change to existing functionality. Content Card components don't allow for text editing (just descriptions). 

However, horizontal card components do include text editors, but the arrangement/layout of text box and image isn't what we were hoping for. 

**Describe the solution you'd like**
A Content card-shaped component with a text editor.

**Describe alternatives you've considered**
Hyperlinks within text boxes, arranged to mimic content cards.

**How will this impact users?**
For czars and smes, another option for displaying info.

**Additional context**

**Comment by rotated8** [comment]
We'll use existing content types instead.
