### ISSUE TITLE
Floating Explorer/sidebar links

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#44]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
An existing module. The Explorers and sidebars currently do not float - they move with the page. For pages with long text this would be helpful.

https://www.drupal.org/project/floating_block 

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
Change to existing functionality. 

**Describe the solution you'd like**
Making either certain components or areas of a page (right sidebar or column) float. 

**Describe alternatives you've considered**
Not having the function. 

**How will this impact users?**
Keeping Explorer box navigation box in sight when scrolling long pages.

**Additional context**
This isn't a crucial request

**Comment by maxdmayhew** [comment]
I think this has styling concerns. We can review this later

**Comment by rotated8** [comment]
Can we get an example page, please?

**Comment by cwbragg** [comment]
Example of long pages with explorer box:
https://libraries.emory.edu/woodruff/collections/borrowing
https://libraries.emory.edu/using-library/borrowing-materials/interlibrary-services/interlibrary-lending-non-emory-libraries
