### ISSUE TITLE
Podcast view for websites

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#45]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
Existing module. 

https://www.drupal.org/project/podcast

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
A problem: Rose Library would like to restart their blog series, and would like it viewable/navigable on the site.

**Describe the solution you'd like**
A view showing Rose Library podcasts. The podcasts would be hosted elsewhere. 

**Describe alternatives you've considered**
A simple hyperlink to a podcast, as currently:

https://libraries.emory.edu/rose/research-learning/rose-library-presents

**How will this impact users?**
A much simpler way to access podcasts directly from within the website!

**Additional context**

**Comment by maxdmayhew** [comment]
not a lot of support for this module. 

Where are the podcasts hosted?
There are a number of ways to accomplish this goal.

**Comment by rotated8** [comment]
This will need additional scope work to define what "done" looks like.

**Comment by cwbragg** [comment]
This can be backlogged - it will take the Rose team a while to work out what they would like. I informed them that iTunes or YouTube would be the best hosting solution, and we can build up a block to pull in the feed.

**Comment by cwbragg** [comment]
Close for now. When Rose wants to revisit, I'll create a new ticket.
