### ISSUE TITLE
Add proactive chat widget (Springhare LibChat) to several Woodruff Library pages

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#48]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
New functionality for Woodruff, but not for Oxford - they already have the Springhare LibChat (proactive) widget in place (hovering at bottom of screen on any page)

About the widget:
https://ask.springshare.com/libanswers/faq/1781

Oxford example:
https://oxford.library.emory.edu

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
Problem - Access Services is hoping to address the downward trend in reference consults. Oxford has seen an uptick in consults due to their widget, over 25%!

**Describe the solution you'd like**
A chat widget available on the Woodruff section of the site, available on a handful of pages:

The pages initially targeted for proactive chat placement are as follows: 
1.       Woodruff Library Page: https://libraries.emory.edu/woodruff 
2.       Woodruff Library Visitor Page: https://libraries.emory.edu/woodruff/visitor-information 
3.       Woodruff Library Building Page: https://libraries.emory.edu/maps/woodruff-library-building 

**Describe alternatives you've considered**

Although Springhare stats that the widget can be added to individual pages, some research would need to happen to see if this is possible, or if the widget would only be available for the entire multi-site. If it's the second, then discussions between library leaders would need to take place.

**How will this impact users?**
Given the increase in consults at Oxford, I'd say this would be a win for our patrons. 

In our Web Governance meeting, Health stated that they would not be interested in proactive chat, so getting the widget to appear on certain pages would be the best/easiest way forward.

A new service like this could be a stressor on teams if they don't have good workflows in place.

**Additional context**

Proactive chat is a readily available feature in our Springshare platform and does not require an additional subscription or fee to implement. You can learn more about Springshare’s proactive chat feature via the following:  

1.       https://buzz.springshare.com/springynews/news-40/proactive-chat
2.       https://springyu.springshare.com/courses/libanswers/libchat-setup
3.       https://blog.springshare.com/2018/10/12/libanswers-proactive-chat-increases-user-engagement/

**Comment by cwbragg** [comment]
Lyndon has sent the chat widget code and a preview guide page to show how it should look:

We have the final chat widget code. Also, here is a link to our test page so that you can see how it should appear: https://guides.libraries.emory.edu/c.php?g=1359498 


Here are the two portions of the chat widget code:
 
<script src=https://emory.libanswers.com/load_chat.php?hash=fd501fd32dcbf5e717b840d4e2fba925aa8ae03d64163e5f75c88f7d12b31824></script>
 
<div id="libchat_fd501fd32dcbf5e717b840d4e2fba925aa8ae03d64163e5f75c88f7d12b31824"></div>
 
The script is “supposed” to go in the head of the page, but doesn’t have to. The second part is supposed to go where you want the widget, but on our test LibGuide it didn’t seem to matter where I put it, either.
 
Important: If we want to limit the height of the widget, we need to add this to the CSS on the page we’re using (or the entire site, if it’s OK, it won’t affect anything else on the website:
 
#s-lch-widget-26362 {
max-width: 300px;
max-height: 600px;
margin-top: auto;
}

**Comment by CB987** [comment]
<img width="289" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk9WQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--477464e787a4779e6fc0ab73fb2ffadf8835a546/Screenshot%202024-02-27%20at%208.32.54%E2%80%AFPM.png" alt="Screenshot 2024-02-27 at 8.32.54 PM.png" />
It's unexpected but it seemed to work without the ID?

**Comment by CB987** [comment]
<img width="508" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67c5cc72bca72085cce2155b91a84b1df9ec08da/Screenshot%202024-02-28%20at%2011.43.50%E2%80%AFAM.png" alt="Screenshot 2024-02-28 at 11.43.50 AM.png" />
connection good, ID seems to be working now and the chat bubble/popup is only showing up on the 3 specified pages.

**Comment by CB987** [comment]
for posterity:
<img width="588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f0b55f80e0f07f279d0dd84953c16537cad9f0b/image.png" alt="image.png" />
