### ISSUE TITLE
Display a publication feed on the library staff pages.

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-enhance#5]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
Integrate Interfolio publication feed into the libraries staff page template.

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
Right now staff are only able to show their academic achievements via a CV link.  

**Describe the solution you'd like**
Staff would like the content they enter into Interfolio on their directory page.

**Describe alternatives you've considered**
Status quo (i.e., continuing to use the CV uploaded as a link).

**How will this impact users?**
This will make it easier for librarians that use interfolio to maintain their CV.

**Additional context**

**Comment by CB987** [comment]
We need a little bit more information about what the publication feed on Interfolio looks like to figure out how we would have to display it on the page. Is it a “feed” like a blog feed? or is it more like a pdf or url link that is updated on the interfolio side? or does it want to be an embedded page?

**Comment by rosy1280** [comment]
This request came from the health sciences library and they were hoping to get something like what the school of medicine has.  However, the school of medicine is using something different than interfolio, and as far as we know, the interfolio feed isn't being used on campus nor does it do the same thing as the school of medicine's tool.

**Comment by CB987** [comment]
As of discussion this morning in the #acquia-drupal-migration slack channel, and per Cari, we're going to put this back into backlog with low priority, as Interfolio doesn't have this feature, but if we can implement something else to fulfill the request, we are happy to try it.

**Comment by maxdmayhew** [comment]
moving back to low prio in backlog @cwbragg @CB987

**Comment by maxdmayhew** [comment]
This doesn't sound possible. What should we do with issues like this? Do we want to keep them somewhere as like wishes or our hopes and dreams? @rotated8 @lovinscari
