### ISSUE TITLE
Create release version in footer

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/web-enhance#6]
In order to make it easier for us to know what version of our sites is running, we would like to include our release numbers in the footer. This is something that work do for our Digital Collections Application and our Library Search Application.

Acceptance Criteria
 the footer should include the release version of the application; the release version should be included programatically
 ideally the last updated date would also be included in the footer.
 the information should appear just above the copyright line

**Comment by maxdmayhew** [comment]
for the sake of reducing redundant tickets, I am going to close out the other existing one and start posting any updates here. 

https://app.zenhub.com/workspaces/library-website-6176fec507eb0000126ee8e1/issues/gh/emory-libraries/d9-emory-libraries/586

Currently looking into a custom view that can pull the current release version via the github api.

**Comment by CB987** [comment]
PR #838

**Comment by CB987** [comment]
[screenshot](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0c1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ae29381c68129d3d4c6a211bd603e27bd9a3fcb/Screenshot%202023-11-08%20at%207.09.17%E2%80%AFPM.png)
