### ISSUE TITLE
Modify exhibits page to include location

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/web-enhance#8]

**Comment by lovinscari** [comment]
the [on-site exhibits page](https://libraries.emory.edu/events-exhibits/exhibits/exhibits-onsite) doesn’t include the location of the exhibit. Work with members of the CCR team to revise

**Comment by CB987** [comment]
moved locations up out of disabled in /admin/structure/types/manage/exhibition/display/card
and
added location field in /admin/cohesion/templates/content_templates/node/node_exhibition_card/edit
i also added it as a field in the view but that didn’t do anything by itself, so idk if necessary

**Comment by CB987** [comment]
![image.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/a8bf2023-6066-4aff-86eb-d80d89b28454)
so far-- getting input from Colin Bragg on more specifics.

**Comment by CB987** [comment]
![image.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/22ccbfa0-2b8f-45a0-b956-a9366b242d05)
![image.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/4cc16010-ce85-4e5f-99d1-8a3a3011313e)
experimenting with different ways of and level of detail in displaying the location. this is doing building-level-room.
the first image is using location-- but rose's official location is so big that it causes the one line to run over.

**Comment by CB987** [comment]
Requested to add level as well.

**Comment by CB987** [comment]
![image.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/317fe576-25c0-49a6-ace8-7ed3eb585471)
@cwbragg does this work for location and level?

**Comment by CB987** [comment]
feedback from Colin Bragg:
Two questions based on the design above:
can ‘Level 1’ either be moved closer to ‘Robert W. Woodruff Library’, with both separated by a comma, or maybe placed below ‘Robert W. Woodruff Library?’
2. Could there be a space between the main title and “Exhibition Details?”
3. Likewise, a space between the location and main title?

**Comment by CB987** [comment]
![Screenshot 2023-07-27 at 6.20.32 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/9eeb8353-b68b-4a6a-92a2-911af1fe81cc)![Screenshot 2023-07-27 at 6.22.00 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/fc8727ff-47e0-4b93-8c48-d2b4df84ef0e)

**Comment by CB987** [comment]
![Screenshot 2023-07-27 at 6.26.09 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/3eace926-a19a-4fca-b097-f8f82278e017)![Screenshot 2023-07-27 at 6.26.25 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/585098ea-b95a-4c53-9e31-55c0eec6c79f)

**Comment by CB987** [comment]
@cwbragg the second set of screenshots is with 10px added 
on either side of the title (and perhaps the people titling them should keep in mind they should fit on 2 lines? i deleted the location out of Dr. McDaniels' exhibition so they don't overrun, but the only other way to do it would be changing the size of the card which will have a ripple effect!)
and dropped the level down below the building. what do you think?

**Comment by cwbragg** [comment]
@CB987 Looking good! Let me run these by Christian. I just noticed that weird Rose Library one from an earlier example. I wonder where that would show up?

**Comment by cwbragg** [comment]
Also, I definitely like the level under the location, and the space between everything.

**Comment by CB987** [comment]
![Screenshot 2023-07-27 at 7.10.27 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/b8501055-fa47-455e-8eb3-6ad51d989dd9)![Screenshot 2023-07-27 at 7.11.05 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/9e925d24-4071-4629-98fe-5103bcbee01b)

**Comment by CB987** [comment]
![Screenshot 2023-07-27 at 7.27.49 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/c6ebc846-2619-491d-8334-51c7db9dc299)![Screenshot 2023-07-27 at 7.28.18 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/84e15db6-c02d-4d2f-acbd-0c3e876b5f5e)

**Comment by CB987** [comment]
@cwbragg some more options.

**Comment by cwbragg** [comment]
@CB987 I like that last one.

**Comment by CB987** [comment]
PR#[875](https://github.com/emory-libraries/d9-emory-libraries/pull/875)

**Comment by cwbragg** [comment]
@CB987 Ready for deploy to stage

**Comment by cwbragg** [comment]
The work has been completed.
